baseurl = "/"
theme = "hello-friend-ng"
languageCode = "en-us"

title = "Tommaso Pifferi"

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[taxonomies]
  tag = "tags"
  
[params]
  dateform = "Jan 2, 2006"
  dateformShor = "Jan 2"
  dateformNum = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  DefaultContentLanguage = "en"
  description = "Homepage and microblog by Tommaso Pifferi"
  keywords = "homepage, blog, developer, full stack, javascript, nodejs, elm, elixir"
  images = [""]

  homeSubtitle = "Full stack developer"
  feedUrl = "https://medium.com/feed/@neslinesli93"

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

  [params.logo]
    logoText = "$ cd ~"
    logoHomeLink = "/"

  # Social icons
  [[params.social]]
    name = "email"
    url = "mailto:p.tommy93@gmail.com"

  [[params.social]]
    name = "github"
    url = "https://github.com/neslinesli93"

  [[params.social]]
    name = "medium"
    url = "https://medium.com/@neslinesli93"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
  [[menu.main]]
    identifier = "works"
    name = "Works"
    url = "/works"
